export const FETCH_WORKSHOPS = 'FETCH_WORKSHOPS';
export const FETCH_WORKSHOPS_FAIL = 'FETCH_WORKSHOP_FAIL';
export const FETCH_WORKSHOPS_SUCCESS = 'FETCH_WORKSHOPS_SUCCESS';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FILTER_CATEGORY = 'FILTER_CATEGORY';

export const FETCH_WORKSHOP = 'FETCH_WORKSHOP';
export const FETCH_WORKSHOP_FAIL = 'FETCH_WORKSHOP_FAIL';
export const FETCH_WORKSHOP_SUCCESS = 'FETCH_WORKSHOP_SUCCESS';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const SELECT_NUMBER_OF_TICKETS = 'SELECT_NUMBER_OF_TICKETS';
export const ADD_TO_CART = 'ADD_TO_CART';

export const POST_ORDERS = 'POST_ORDERS';
export const POST_ORDERS_FAIL = 'POST_ORDERS_FAIL';
export const POST_ORDERS_SUCCESS = 'POST_ORDERS_SUCCESS';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';

export const SET_PRODUCT_QUANTITY = 'SET_PRODUCT_QUANTITY';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';

export const LOADING_WORKSHOPS = 'LOADING_WORKSHOPS';
export const LOADING_USERS = 'LOADING_USERS';
export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const LOADING_WORKSHOP = 'LOADING_WORKSHOP';
