export const FETCH_WORKSHOPS = 'FETCH_WORKSHOPS';
export const FETCH_WORKSHOPS_FAIL = 'FETCH_WORKSHOP_FAIL';
export const FETCH_WORKSHOPS_SUCCESS = 'FETCH_WORKSHOPS_SUCCESS';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FILTER_CATEGORY = 'FILTER_CATEGORY';

export const FETCH_WORKSHOP = 'FETCH_WORKSHOP';
export const FETCH_WORKSHOP_FAIL = 'FETCH_WORKSHOP_FAIL';
export const FETCH_WORKSHOP_SUCCESS = 'FETCH_WORKSHOP_SUCCESS';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const SHOW_CART_LIST = 'SHOW_CART_LIST';

export const LOADING_WORKSHOPS = 'LOADING_WORKSHOPS';
export const LOADING_USERS = 'LOADING_USERS';
export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const LOADING_WORKSHOP = 'LOADING_WORKSHOP';
